### ISSUE TITLE
Integrate with now

### ISSUE THREAD

**Issue by ebidel** [ebidel/lighthouse-ci#36]
Zeit now (lolz) supports auto-deploying PRs and commits: https://zeit.co/blog/now-for-github

We should have an easy path for users that want to use this as their deployment vehicle.

**Comment by soleo** [comment]
@ebidel  I'd love to look into this issue

**Comment by wyze** [comment]
I built a small little package to help with this: [wait-for-now](https://github.com/wyze/wait-for-now)

I got it to work with the jobs syntax like so:

```yaml
    - stage: lighthouse
      if: type = pull_request
      install: yarn add --dev ebidel/lighthouse-ci wait-for-now
      script: lighthouse-ci "$(wait-for-now)"
```

See: https://github.com/wyze/wyze.github.io/blob/bd71f4ac9e843886f4f6c530415aab3280d558dc/.travis.yml#L28-L31

And here is the PR where I added the functionality to my repo: https://github.com/wyze/wyze.github.io/pull/6
