### ISSUE TITLE
Submit lighthouse_ci to Docker hub?

### ISSUE THREAD

**Issue by kmturley** [ebidel/lighthouse-ci#4]
Great work, this tool will be extremely useful for CI builds!

I see you already have Docker source code here:
https://github.com/ebidel/lighthouse-ci/tree/master/builder

Can you submit an official Docker built image to Docker hub? There are a couple of benefits to this approach:

1) This will save everyone the step of downloading and building themselves, and provide an official release which is testable.

2) When using with CI tools, not only does it saves build times, but can be spun up as a service with one line of code, like this selenium example for gitlab and bitbucket pipelines:

.gitlab-ci.yml
```
test_functional:
  image: python
  stage: test
  services:
    - selenium/standalone-chrome
  script:
    - SELENIUM="http://selenium__standalone-chrome:4444/wd/hub" BASE_URL="https://$CI_BUILD_REF_SLUG-dot-$GAE_PROJECT.appspot.com" DRIVER="headless_chrome" python -m unittest discover -s qa
```

bitbucket-pipelines.yml
```
pipelines:
  default:
    - step:
        services:
          - selenium
        script:
          - SELENIUM="http://127.0.0.1:4444/wd/hub" BASE_URL="http://$BITBUCKET_BRANCH.$AWS_PROJECT.us-east-1.elasticbeanstalk.com" DRIVER="headless_chrome" python -m unittest discover -s qa

definitions:
  services:
    selenium:
      image: selenium/standalone-chrome
```
