### ISSUE TITLE
Lighthouse CI score: undefined

### ISSUE THREAD

**Issue by lukasoppermann** [ebidel/lighthouse-ci#7]
Hey, so now I ran it on travis. I get no real errors, but I do get a message `Lighthouse CI score: undefined`. I also do not get a comment in the PR (which makes sense, since the score is undefined). I did not receive a key yet, but the readme sounds like it is not required yet, is that true?

https://travis-ci.org/lukasoppermann/veare/builds/275630036?utm_source=github_status&utm_medium=notification

I want to run the app on travis and test it.

I currently have the following in my travis.yml file.

```yml
before_script: npm install
script:
  - xvfb-run npm run travis
  - NODE_ENV=testing NODE_PORT=8888 node app.js &
  - node node_modules/lighthouse-ci/runlighthouse.js http://localhost:8888
  - pkill node
```

Can you tell me what I am doing wrong? Thank you in advance (btw. I want to run it locally first, if it works fine for a while I will invest some time into the setup with a remote staging server).
